import Head from 'next/head'
import Image from 'next/image'
import Header2 from "../components/header2"
import JobPost from '../components/jobpost'
import { useState, useEffect } from 'react'
import { useRef } from 'react'
import useSWR from 'swr'
import app from '../config/firebase'
import Navbar from '../components/navbar'
import mo1 from '../public/mo1.jpg'




const fetcher = (url) => fetch(url).then((res) => res.json())

import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() { 
  
  
   
  const snake = useRef()
  
  
  const [jobs, setJobs] = useState('')

  const { data, error } = useSWR('/api/startPageJobs', fetcher)

  

  

  
  return (
    <div className="bg-stone-200 h-full w-full background flex flex-col">
      <Head>
        <title>Politik-Jobs.de | Jobs für Referenten, Absolventen und Experten</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />      
      
      
      
      <Header2 jobs={jobs} setJobs={setJobs}/>
      
       {        
       (data && jobs == '') ?
       ( data && <div className="md:w-1/2 mr-5">{data.map(job => 
        < JobPost key={job.title} job={job}/>)}
        
      </div> ) : ( jobs && <div className="md:w-1/2 mr-5">{jobs.map(job => 
        < JobPost key={job.title} job={job}/>)}
        
      </div> )
            
      }
      



        <form className="m-4 flex">
          <input className="rounded-l-lg p-4 border-t mr-0 border-b border-l text-gray-800 border-gray-200 bg-white" placeholder="your@mail.com"/>
          <button className="px-8 rounded-r-lg bg-yellow-400  text-gray-800 font-bold p-4 uppercase border-yellow-500 border-t border-b border-r">Subscribe</button>
        </form>
        
      </div>
     

      

   
  )
}

